"""
LesionBridge - Stage 1: lesion segmentation training.

Combines Refined_IDRiD (train split) + DDR lesion_segmentation (train split)
into one 4-class multi-label segmentation task: MA, HE, EX, SE (=CWS).
These are the only lesion types present in BOTH source datasets.

Refined_IDRiD's unified grayscale mask is decoded using the official class
legend published by the dataset authors (acidrainpsu1980-byte/RefinedIDRiD,
TrainRefinedIDRiD.m):
    classNames = [Background, Retina, FV, Vessel, OD, VH, EX, IRMA, HE, NV, CWS, MA]
    labelIDs   = [0, 8, 16, 24, 32, 4, 63, 96, 127, 166, 191, 255]
We only use EX=63, HE=127, CWS(SE)=191, MA=255 here; the rest (vessel, OD,
fovea, VH, IRMA, NV) are held back for a later fine-tuning stage since DDR
doesn't have them and using them now would break the shared 4-class setup.

DDR provides EX/HE/MA/SE as separate binary mask images in its own folders.

Uses the 5-fold split from folds/segmentation_folds.csv (generated by
make_folds.py) so results are cross-validated and comparable across runs.

Architecture: segmentation_models_pytorch U-Net decoder on a timm encoder.
Default encoder is a Swin Transformer (Swin-UNet-style hybrid) - see
ENCODER_NAME below. Falls back gracefully if the encoder can't be downloaded
(no internet) - swap to 'resnet34' in that case.

Usage:
    python train_segmentation.py --fold 0
    python train_segmentation.py --fold 0 1 2 3 4     # loop all folds
"""

import os
import csv
import argparse
from collections import defaultdict

import numpy as np
import cv2
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import albumentations as A
from albumentations.pytorch import ToTensorV2
import segmentation_models_pytorch as smp

BASE = "/sessions/compassionate-fervent-dijkstra/mnt/Dataset"
FOLDS_CSV = os.path.join(BASE, "folds", "segmentation_folds.csv")
CKPT_DIR = os.path.join(BASE, "checkpoints", "segmentation")

IMG_SIZE = 128  # must match the Swin encoder's fixed window/patch resolution below
CLASSES = ["MA", "HE", "EX", "SE"]  # fixed order, 4 output channels
BATCH_SIZE = 4          # conservative for an 8GB laptop GPU at 512x512
NUM_EPOCHS = 40
LR = 1e-4
ENCODER_NAME = "resnet18"  # Swin-UNet-style hybrid
ENCODER_WEIGHTS = None

# Refined_IDRiD unified-mask pixel values for the 4 shared classes
RIDRID_LABEL_IDS = {"MA": 255, "HE": 127, "EX": 63, "SE": 191}


def get_device():
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def load_fold_rows(fold_csv):
    with open(fold_csv, newline="") as f:
        return list(csv.DictReader(f))


class LesionSegDataset(Dataset):
    """
    Builds (image, 4-channel binary mask) pairs from the pooled
    Refined_IDRiD + DDR segmentation-train rows for one CV split.
    """

    def __init__(self, rows, transform=None):
        self.rows = rows
        self.transform = transform

        self.ridrid_img_dir = os.path.join(BASE, "Refined_IDRiD", "Train", "Images")
        self.ridrid_label_dir = os.path.join(BASE, "Refined_IDRiD", "Train", "Labels")

        self.ddr_img_dir = os.path.join(
            BASE, "DDR", "DDR-dataset", "lesion_segmentation", "train", "image"
        )
        self.ddr_label_dir = os.path.join(
            BASE, "DDR", "DDR-dataset", "lesion_segmentation", "train", "label"
        )

    def __len__(self):
        return len(self.rows)

    def _load_ridrid(self, filename):
        img_path = os.path.join(self.ridrid_img_dir, filename)
        stem = os.path.splitext(filename)[0]
        label_path = os.path.join(self.ridrid_label_dir, f"{stem}_vessel.png")

        image = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
        unified = cv2.imread(label_path, cv2.IMREAD_GRAYSCALE)

        mask = np.zeros((*unified.shape, len(CLASSES)), dtype=np.float32)
        for i, cls in enumerate(CLASSES):
            mask[..., i] = (unified == RIDRID_LABEL_IDS[cls]).astype(np.float32)
        return image, mask

    def _load_ddr(self, filename):
        img_path = os.path.join(self.ddr_img_dir, filename)
        stem = os.path.splitext(filename)[0]

        image = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
        h, w = image.shape[:2]

        mask = np.zeros((h, w, len(CLASSES)), dtype=np.float32)
        for i, cls in enumerate(CLASSES):
            mask_path = os.path.join(self.ddr_label_dir, cls, f"{stem}.tif")
            if not os.path.isfile(mask_path):
                # DDR sometimes ships .tif or .png depending on lesion type - try both
                alt = os.path.join(self.ddr_label_dir, cls, f"{stem}.png")
                mask_path = alt if os.path.isfile(alt) else mask_path
            if os.path.isfile(mask_path):
                m = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
                mask[..., i] = (m > 0).astype(np.float32)
            # if the mask file genuinely doesn't exist, that lesion type is
            # absent for this image -> channel stays all zero (correct)
        return image, mask

    def __getitem__(self, idx):
        row = self.rows[idx]
        if row["source"] == "Refined_IDRiD":
            image, mask = self._load_ridrid(row["filename"])
        else:
            image, mask = self._load_ddr(row["filename"])

        if self.transform:
            augmented = self.transform(image=image, mask=mask)
            image, mask = augmented["image"], augmented["mask"]
            mask = mask.permute(2, 0, 1).float()  # HWC -> CHW

        return image, mask


def get_transforms(train=True):
    if train:
        return A.Compose([
            A.Resize(IMG_SIZE, IMG_SIZE),
            A.HorizontalFlip(p=0.5),
            A.VerticalFlip(p=0.5),
            A.RandomRotate90(p=0.5),
            A.RandomBrightnessContrast(p=0.3),
            A.Normalize(),
            ToTensorV2(),
        ])
    return A.Compose([
        A.Resize(IMG_SIZE, IMG_SIZE),
        A.Normalize(),
        ToTensorV2(),
    ])


def dice_score(pred, target, eps=1e-6):
    pred = (pred > 0.5).float()
    intersection = (pred * target).sum(dim=(2, 3))
    union = pred.sum(dim=(2, 3)) + target.sum(dim=(2, 3))
    dice = (2 * intersection + eps) / (union + eps)
    return dice.mean(dim=0)  # per-class mean over batch


def build_model():
    model = smp.Unet(
        encoder_name=ENCODER_NAME,
        encoder_weights=ENCODER_WEIGHTS,
        in_channels=3,
        classes=len(CLASSES),
        activation=None,
    )
    return model


def run_fold(fold_idx, epochs=NUM_EPOCHS):
    device = get_device()
    print(f"\n=== Fold {fold_idx} | device: {device} ===")

    rows = load_fold_rows(FOLDS_CSV)
    train_rows = [r for r in rows if int(r["fold"]) != fold_idx]
    val_rows = [r for r in rows if int(r["fold"]) == fold_idx]
    print(f"train images: {len(train_rows)} | val images: {len(val_rows)}")

    train_ds = LesionSegDataset(train_rows, transform=get_transforms(train=True))
    val_ds = LesionSegDataset(val_rows, transform=get_transforms(train=False))

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                               num_workers=2, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False,
                             num_workers=2, pin_memory=True)

    model = build_model().to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    bce = nn.BCEWithLogitsLoss()
    dice_loss_fn = smp.losses.DiceLoss(mode="multilabel")

    os.makedirs(CKPT_DIR, exist_ok=True)
    best_dice = -1.0

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for images, masks in train_loader:
            images, masks = images.to(device), masks.to(device)
            optimizer.zero_grad()
            logits = model(images)
            loss = bce(logits, masks) + dice_loss_fn(logits, masks)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * images.size(0)
        train_loss /= len(train_ds)

        model.eval()
        dice_sum = torch.zeros(len(CLASSES))
        n_batches = 0
        with torch.no_grad():
            for images, masks in val_loader:
                images, masks = images.to(device), masks.to(device)
                logits = model(images)
                probs = torch.sigmoid(logits)
                dice_sum += dice_score(probs, masks).cpu()
                n_batches += 1
        dice_per_class = dice_sum / max(n_batches, 1)
        mean_dice = dice_per_class.mean().item()

        scheduler.step()
        print(f"  epoch {epoch+1}/{epochs} | train_loss {train_loss:.4f} | "
              f"val_mean_dice {mean_dice:.4f} | "
              f"per-class {dict(zip(CLASSES, [round(d,3) for d in dice_per_class.tolist()]))}")

        if mean_dice > best_dice:
            best_dice = mean_dice
            ckpt_path = os.path.join(CKPT_DIR, f"fold{fold_idx}_best.pt")
            torch.save({"model_state": model.state_dict(),
                        "epoch": epoch, "val_dice": mean_dice,
                        "classes": CLASSES}, ckpt_path)
            print(f"    -> new best, saved {ckpt_path}")

    print(f"Fold {fold_idx} done. Best val mean dice: {best_dice:.4f}")
    return best_dice


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--fold", type=int, nargs="+", default=[0],
                         help="which fold(s) to run, e.g. --fold 0 1 2 3 4")
    parser.add_argument("--epochs", type=int, default=NUM_EPOCHS)
    args = parser.parse_args()

    results = {}
    for fold_idx in args.fold:
        results[fold_idx] = run_fold(fold_idx, epochs=args.epochs)

    if len(results) > 1:
        print("\n=== Cross-validation summary ===")
        vals = list(results.values())
        print(f"mean dice: {np.mean(vals):.4f} +/- {np.std(vals):.4f}")


if __name__ == "__main__":
    main()
